### ISSUE TITLE
network detection does not work through a proxy (squid)

### ISSUE THREAD

**Issue by kpiris** [LedgerHQ/ledger-live-desktop#1073]
#### Ledger Live Version and Operating System

- Ledger Live 1.0.1
- Platform: linux

When the manager is opened, ledger live checks Internet connectivity.

If I have a proxy (configured via environment variables), the program does not detect that connectivity, it shows a red message “Oops, internet seems down” and offers to retry; which never detects it (see attached screenshot ledger-live.proxy-netdown.png).

On my squid3 logs I have messages like this one: “TAG_NONE/400 4062 NONE error:invalid-request - HIER_NONE/- text/html”

If I unset proxy environment variables, then network detection, and the program, works fine.

I could attach application.log if you need it, I’m guessing you won't since I've been able to reproduce it on two different computers (one with debian sid, the other with debian stretch, both updated to date).

Thanks
![ledger-live proxy-netdown](https://user-images.githubusercontent.com/20923872/42616168-88437272-85ad-11e8-86bf-4aa24452692c.png)

**Comment by gre** [comment]
I guess because we use WebSocket here.
Not sure if there is anything we can fix

**Comment by lomax** [comment]
https://stackoverflow.com/questions/38974731/websockets-not-connected-behind-proxy here is the suggestion how you could fix it.

**Comment by lomax** [comment]
@meriadec Have you tested it behind the proxy? It just can't detect internet connection behing the proxy which allow CONNECT only on 443 port and block all other ports except 80 and 443. @kpiris said he could provide any logs if needed as he manage the proxy himself. What additional info do you need?

**Comment by meriadec** [comment]
We can't test with your proxy :smile:
As described before, it's not an issue with the app, but with some external infrastructure blocking app normal behaviour.

If you find a workaround in the app that works for you and doesn't bring any regression without proxy, you can totally make a pull request (if you do so, please provide any useful instructions for us to test). Thanks!

**Comment by lomax** [comment]
@meriadec Can you please name proxy and describe settings you've used to test the app connectivity through the proxy. Me and @kpiris reported that the app doesn't work behind the squid proxy. Could you elaborate if this is the problem with proxy in general why you are claiming proxy instance and not the app?

**Comment by meriadec** [comment]
Dude, like I said two times, we **didn't tested any proxy configuration**: it's not part of the app scope. As described *in the issue decription*: the app works fine without proxy. We can't do custom fixes for users custom configuration.

So repeating again: If you want to propose a fix yourself, it will be welcomely welcome.

Have a good day.

**Comment by lomax** [comment]
But old Chrome apps works behind the proxy. You've created the new standalone app that doesn't. I can give you a hint it is called regression and not "users custom configuration". Because proxies and firewalls is the common network infrastructure. You've just reduced connectivity options and saying that users must take care of it themselfs.

**Comment by meriadec** [comment]
you can also try setting the environment variable `BASE_SOCKET_URL` to `ws://api.ledgerwallet.com/update`

**Comment by lomax** [comment]
![image](https://user-images.githubusercontent.com/691748/42684809-e40cc968-8699-11e8-874b-39318a4840a4.png)
The browser prevents me to initiate connection to unsecure socket ws://
`
echo.js:136 Mixed Content: The page at 'https://www.websocket.org/echo.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://echo.websocket.org/?encoding=text'. This request has been blocked; this endpoint must be available over WSS.
doConnect @ echo.js:136
echo.js:136 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at HTMLButtonElement.doConnect (https://www.websocket.org/js/echo.js:136:17)
`

**Comment by gre** [comment]
@lomax can you try to click on CONNECT, not the "Rock it" thing

<img width="538" alt="capture d ecran 2018-07-13 a 11 48 20" src="https://user-images.githubusercontent.com/211411/42685215-acb625f6-8692-11e8-83c2-ddf533e418f8.png">

**Comment by lomax** [comment]
> you can also try setting the environment variable BASE_SOCKET_URL to ws://api.ledgerwallet.com/update

![image](https://user-images.githubusercontent.com/691748/42685226-141a3eb4-869b-11e8-84c8-a079873d1ba7.png)

**Comment by lomax** [comment]
@gre I've got those errors after i click disconnect on wss://, changed it to ws:// and clicked connect.
wss:// work just fine as you see from the screenshot.
So I think that something wrong with the app and not the proxy as proxy pass wss://echo.websocket.org just fine. Could you place some test script on the Web that uses the same functions to open wss that in the app to test it from the browser?

**Comment by lomax** [comment]
I've tried http://echo.websocket.org to check ws:// and it indeed doesn't work
![image](https://user-images.githubusercontent.com/691748/42687039-78cc8e70-86a0-11e8-8ff2-46b3b6eb5910.png)
And for some reason i see request to wss:// from this page and to the different fqdn.

**Comment by lomax** [comment]
https:// wss:// session
![image](https://user-images.githubusercontent.com/691748/42687391-62a03876-86a1-11e8-94d1-883860d0fba1.png)

**Comment by maciejbozemoj** [comment]
any updates or plans to revert to Chrome ledger wallet app?

**Comment by danuker** [comment]
@maciejbozemoj I guess a workaround would be to run everything in a virtual machine, and configure the VM to use the proxy.

**Comment by gre** [comment]
we might provide an option to set up the proxy parameters.

https://github.com/electron/electron/blob/master/docs/api/session.md#sessetproxyconfig-callback

**Comment by GreatBigWhiteWorld** [comment]
Any ETA on the update to support proxy?

**Comment by gre** [comment]
Please try again. We believe this issue is now fixed and was due to cloudfare.

**Comment by lomax** [comment]
Nope, it doesn't ->
[ledger-1.8.0-error.log](https://github.com/LedgerHQ/ledger-live-desktop/files/3190187/ledger-1.8.0-error.log)

**Comment by sargonpiraev** [comment]
any updates?

**Comment by cryptochrome** [comment]
The guys at Ledger are such greenhorns who have next to zero clue. They call proxy servers "uncommon" and "non-standard". Half of the fucking world is accessing the internet through proxies, you idiots. Basically anyone accessing from company networks goes through proxies.

**Comment by GreatBigWhiteWorld** [comment]
What's shocking to me is the fact that after such long time the dev said it's fixed now while it clearly isn't fixed at all.

**Comment by gre** [comment]
It has been confirmed by many users that we improved the initial situation (we had cloudflare issues) so that's why I assumed the initial issue was fixed (specifically the one showing a live saying internet seems down), this issue has been created more than a year ago and there might be many reason of why you are experiencing network issues.

It can be good to have more detail because "it does not work" does not really help understanding the problem about what happens on your side (you can provide directly to the techsupport team). Alternatively if you are a developer you can investigate to give us precise detail on how we should reproduce the problem, no one at Ledger have this issue.
Thanks

**Comment by bozemojmaciej** [comment]
We are not connecting directly to the internet, so we also can't connect directly to your servers.
If you will have isolated network with Proxy server set as an the only gateway to internet you will be able to reproduce this issue.
![Proxy](https://user-images.githubusercontent.com/17525316/69781426-6f72d600-11ae-11ea-83dc-5db034a49d63.png)

**Comment by gre** [comment]
ok, sorry i confonded this task with another one that was issuing the same manager error. So that's why this task is still opened, we can introduce this feature (and in fact, Ledger Live Desktop is open sourced so anyone wanting to take this is welcomed to 🙏 )

**Comment by NightProwler-dc** [comment]
Any progress at all after two  years?

**Comment by gre** [comment]
It's hard to understand exactly the needs and the constraints. What exactly are you looking for @NightProwler-dc ?

We are not aware of a lot of users actively asking for this feature so the best is probably to have OSS contribution on this. We are open source and we can take the time to review a Pull Request proposal of a solution.

dev note: In term of architecture, if it means a proxy on the HTTP, we have also to understand this need to be solved both on Electron side and in our internal node process side.

**Comment by cvila84** [comment]
Hello all !

I have just bought a nano S and now I'm struggling as I'm behind a proxy (just like a lot of other people who are working from home on a corporate machine which requires a proxy). I just read the whole thread and I'm astonished by your arguments. This project is indeed OSS but since you are selling HW which work with this SW, we are no longer in a pure OSS context where you can just claim that you will wait for a PR coming outside from your company for a clearly standard use-case. If you have product owners, they should understand the business value of this request and ask your teams to work on it ASAP.

I should have checked this before buying your product, now I'm a bit disappointed here, especially because you are a french company and I should be proud of you as I am a french citizen.

Cheers

**Comment by gre** [comment]
@cvila84 Could you detail a bit more precisely what is your setup and your need? What kind of proxy? Is it using something like SOCKS?

I don't understand why you expect Ledger Live to solve this, as far as I'm seeing, at least on Mac, even Chrome don't have that settings available, instead they link you to the System configuration where you can set it up.
It seems to be the same on Windows, it's a global system configuration,
https://www.expressvpn.com/fr/support/troubleshooting/google-chrome-no-proxy/

**Comment by cvila84** [comment]
@gre thanks for your answer !

Let me clarify a bit my situation which is probably the situation of a lot of other people that have to live with proxies. I know how to set/unset the proxy on my system and yes, the application is working very well when I'm unsetting the proxy.

The problem is I must use a HTTP proxy when I'm connected to my corporate network because of the VPN gateway firewall rules that force all the communication to go towards the VPN network through this HTTP proxy.

I made some tests with a simple squid proxy (as it is shipped with Ubuntu 20.04 LTS) and I think there is actually a problem on client side. When trying to access ledger API in HTTPS, instead of performing a HTTP CONNECT to the proxy and then perform the TLS session with the ledger servers, it directly asks the proxy to perform the GET/POST requests to API in HTTPS. This way of working should be reserved to unsecured HTTP requests. For the HTTPS requests, the TLS session shall be done by the client, not the proxy !

That said, the HTTPS requests done by the proxy should work even if this is not secured from a client perspective. I took a look to the tcpdump logs of squid and it appears the TLS handshake cannot be done because the server expects the SNI extension to be provided by the client. And because the SNI is only known by the client, the proxy will never be able to do the HTTPS requests by itself.

As a conclusion, the HTTP proxy client implementation in ledger live is faulty when HTTPS requests have to be done.

Hope it clarifies the situation !

**Comment by GreatBigWhiteWorld** [comment]
> @cvila84 Could you detail a bit more precisely what is your setup and your need? What kind of proxy? Is it using something like SOCKS?
> 
> I don't understand why you expect Ledger Live to solve this, as far as I'm seeing, at least on Mac, even Chrome don't have that settings available, instead they link you to the System configuration where you can set it up.
> It seems to be the same on Windows, it's a global system configuration,
> https://www.expressvpn.com/fr/support/troubleshooting/google-chrome-no-proxy/

I don't understand how hardware wallet devs can't understand a simple issue after two years which is basically:

**Some core function in Ledger Live (manager) doesn't work behind a proxy environment. It has nothing to do with how proxy is set up via system or app settings!**

Steps to produce:
1. Setup a http system proxy in OS (e.g. Tor uses http://127.0.0.1:9050). (Please google how to setup a proxy for Windows/Linux system)
2. Run Ledger Live.
3. Click on manager.
4. Connect a ledger device and unlock.
5. Manager shows ledger unlocked and a blank screen forever.
 
I personally have to turn on/off system proxy for ledger live to work. Nonetheless I'm so shocked their devs just say they don't understand the issue after two years, which is worse than a "don't care" attitude. That said, I have lost all my trust here.

**Comment by eddieparker** [comment]
FWIW I have the same issue and wish it was supported natively.  That said, a work around I have is to set a custom route to avoid my proxy and go direct (may not work for whatever proxy you have), and this is windows syntax:

`route add 104.0.0.0 MASK 255.0.0.0 192.168.1.254 metric 1`

Basically I'm adding a route to 104.x.x.x through my gateway of 192.168.1.254 (yours may be different) and setting it to a high metric.  This makes me go through a direct connection and bypass the proxy altogether.  Again, may not be useful if you *require* a proxy, but posting it in case it helps someone.

**Comment by cvila84** [comment]
@gre any updates ? I spent some time to provide you very detailed information about the issue, and now I believe it should not be that hard to fix it (or ask a fix if it is on 3rd party side). Thanks for your help :)

**Comment by gre** [comment]
> Some core function in Ledger Live (manager) doesn't work behind a proxy environment. It has nothing to do with how proxy is set up via system or app settings!

> Steps to produce:
>
> - Setup a http system proxy in OS (e.g. Tor uses http://127.0.0.1:9050). (Please google how to setup a proxy for Windows/Linux system)
> - Run Ledger Live.
> - Click on manager.
> - Connect a ledger device and unlock.
> - Manager shows ledger unlocked and a blank screen forever.

Unfortunately I'm not able to reproduce the problem. I'm using Tor on localhost:9050, set it up widely on my system (i can confirm my IP changes), and yet, I can use Ledger Live (testing on on Mac) and access the Manager, see and install apps without any issue (countervalues and blockchain services works as well).

**Comment by cvila84** [comment]
Quick search on axios gives https://github.com/axios/axios/issues/925

**Comment by gre** [comment]
Would you mind sharing your environment regarding proxy? `printenv | grep -i proxy`
I have a potential fix in one of our library but it's still a blind fix from my side (from information I could find in these axios discussion) and I will need to have a reproductible environment.

Thanks!

**Comment by cvila84** [comment]
@gre not sure if the question is for me but just in case, I'm a Windows user and to test, I installed a squid proxy on my other machine under Linux. I'm then using HTTP_PROXY=http://unix-host:3128 and HTTPS_PROXY=http://unix-host:3128

**Comment by cvila84** [comment]
@gre what is the next step ? do you plan to issue a new version so I can test ?

**Comment by gre** [comment]
Unfortunately the current attempt didn't work and we'll need more resources to continue on this Draft PR.

cc @juan-cortes let's chat tomorrow on this

**Comment by ledgetest** [comment]
@gre @cvila84 

> Unfortunately I'm not able to reproduce the problem.

I have also the proxy problem.

To reproduce the problem i would recommend you to create a Live Linux USB stick where the whole traffic runs automatically through a proxy. Not much to do here.

As example Tails OS with TOR:

https://tails.boum.org

After installation of Ledger Live in Tails the Ledger Live software stops finaly with an error: no internet.

Only Ledger Live doesn't find a internet connection through the proxy. Other software packages including Electrum have internet connection.

**Comment by gre** [comment]
@juan-cortes in our team has been able to reproduce as well as identify where the issue was coming from. A work in progress is in https://github.com/LedgerHQ/ledger-live-desktop/pull/3545. however we still need to figure out how to handle properly http vs https (need more precision from @juan-cortes)

**Comment by ndreisg** [comment]
A little hint for all the squid users here: http://lists.squid-cache.org/pipermail/squid-users/2018-July/018583.html
Not sure if this post is still up2date but at least back in 2018 squid didn't support native websocket connections

**Comment by DosPuppet** [comment]
Same problem here, several person who need to use ledger live, but they are behind a proxy. It's a no go. 
I reproduce it easily on a local windows with a squid, and yes, the direct get doesn't work. 
Tried @gre build (https://github.com/juan-cortes/ledger-live-desktop/tree/proxy-fix-test) and this one works like a charm (http and https proxy vi squid), but it's an older version. 

Any news for an evolution in the main branch ?

Thanks.

**Comment by bormiopoli** [comment]
Can you confirm your Cloudfare host accepts all sort of proxy connections? could you catch up with them for the specifications? Up to now sounds like your host may be forbidding proxyfied connections.
