### ISSUE TITLE
"Repair your Ledger device (Bootloader)" doesn't work on Ledger Live 1.8

### ISSUE THREAD

**Issue by highvolt4ge** [LedgerHQ/ledger-live-desktop#1984]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.8
- Platform and version:  Windows 10, 64bit.

#### Expected behavior

Selecting "Repair your Ledger device", following the instructions & reconnecting the device actually does something.

#### Actual behavior

Nothing happens, Bootloader text is stuck on screen.

#### Steps to reproduce the behavior

So I tried to update my Ledger Nano S firmware. 

https://support.ledger.com/hc/en-us/articles/360002731113

"Press the left button on your device and hold it while you reconnect the USB cable.
Release the button once Bootloader is displayed." 
After that part my device got stuck, Live Ledger couldn't connect to it, device would not update and "Bootloader" text did stay on screen. Just connecting Ledger without pushing any buttons ends up to instructions to update my firmware.

Selecting Repair in Ledger Live Help-section and then following the instructions did not fix the problem. Ledger Live kept showing me the instructions how to do the repairing. Nothing happened.

1. Install Ledger Live 1.8
2. Setup new Ledger Nano S
3. Try to update firmware
4. Follow the instructions
5. Device gets stuck on part 6

I got this fixed by downgrading to Ledger Live 1.7. Somehow the repairing tool in 1.7 works and I finally got my device firmware updated.

**Comment by gre** [comment]
Thanks for the report.

we're aware of this (mentioned in 1.8.0 release notes). 1.8.0 broke support of upgrading from 1.3.1 but this is now fixed in our develop branch, will be fixed in next release.

Thanks

**Comment by highvolt4ge** [comment]
My bad then. Downloaded latest version from the official Ledger website, so this time no release notes for me. 

Someone maybe should make pinned post about this issue on Reddit (r/ledger & r/ledgerwallet) since there are growing amount of posts about similiar issues.

**Comment by dboaro** [comment]
Hi, I downgrade the Ledger live to 1.7.0, some how it went through and move from the disconnect re connect cable with left button pushed while connecting cable screen to the manager, than now it is stuck on manager ''connect your device'' screen, it stay loading ''connect and unlock your ledger device'' and won't move from there. 
Already try to update from Ledger live 1.7 to 1.8, same happens. Stuck on ''update'' screen on ledger nano S, reconnect cable won't work either. 
Where Can I find a step by step troubleshooting for this update from 1.3.0 to latest?
How can I move from ''update'' screen on Ledger Nano S? 
Ledger live 1.7 how to move from stuck screen on manager menu ''connect and unlock your ledger'' step?
Ledger live 1.8 how to move from stuck screen on manager menu ''connect and unlock your ledger'' step?

**Comment by dboaro** [comment]
> Thanks for the report.
> 
> we're aware of this (mentioned in 1.8.0 release notes). 1.8.0 broke support of upgrading from 1.3.1 but this is now fixed in our develop branch, will be fixed in next release.
> 
> Thanks

Hi, I downgrade the Ledger live to 1.7.0, some how it went through and move from the disconnect re connect cable with left button pushed while connecting cable screen to the manager, than now it is stuck on manager ''connect your device'' screen, it stay loading ''connect and unlock your ledger device'' and won't move from there.
Already try to update from Ledger live 1.7 to 1.8, same happens. Stuck on ''update'' screen on ledger nano S, reconnect cable won't work either.
Where Can I find a step by step troubleshooting for this update from 1.3.0 to latest?
How can I move from ''update'' screen on Ledger Nano S?
Ledger live 1.7 how to move from stuck screen on manager menu ''connect and unlock your ledger'' step?
Ledger live 1.8 how to move from stuck screen on manager menu ''connect and unlock your ledger'' step?

**Comment by forgetso** [comment]
Hi, I have the same issue on Ledger Live 1.11.0. I was updating from 1.3.X (not entirely sure which version). Now when I try the repair process and enable "bootloader" mode, Ledger Live does nothing. I have tried 3 different versions of Ledger Live on Windows 7 (I know this isn't supported) and Ubuntu 16.

Please let me know how to get my device working!

**Comment by dboaro** [comment]
Hi, I got it fixed with the support help direct from ledger. Try to
describe for them and follow the instructions they will send.
Try starting by downgrade the live version first and then trying to fix the
issue.

*__________________________*

*BOARO, Darlan*

+86 18602143764

**Comment by forgetso** [comment]
Cheers dboaro, I got this fixed by adding the udev rules on ubuntu https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

**Comment by dboaro** [comment]
great

*__________________________*

*BOARO, Darlan*

+86 18602143764

**Comment by Jaegermeiste** [comment]
This is still an issue in 1.15. Just tried to update my device, got stuck at bootloader (as in the 1.7, 1.8 issues), I got the device moving following the Chrome instructions at https://www.reddit.com/r/ledgerwallet/comments/bkf274/fixed_nano_s_stuck_on_bootloader/
This was the Windows version of Ledger Live, freshly installed today (it's been a minute since I plugged in my wallet).

**Comment by XianLabs** [comment]
Holy cow could a product be any worse design-wise?

Bought one a year ago, set it up initially and tried using it now, stuck on update, buttons do nothing. Already tried all the typical troubleshooting, window's can't detect it as a Ledger at all. Recovery button doesn't work, Bootloader gets stuck, etc.

How could you trust such a device? You already have to worry about it being phyiscally stolen or circuit shorted.

**Comment by rahulmanuwas** [comment]
Hi, I had the same issue. Worked with a new laptop - Microsoft Surface Laptop - 1. Didn't work with MacBook Pro 2012 and Dell Inspiron 7560. Hope this helps. All you need to do is **keep finding a new laptop**, install ledger live, go to ledger manager,  plug in your ledger device  while keeping the closest USB Button pressed (for bootloader). The update will resume automatically.  You just need to keep changing your computer until it works.

**Comment by clashthe** [comment]
same issue with latest
