### ISSUE TITLE
Incorrect conversion rate for HOT (HoloToken) ERC20 token

### ISSUE THREAD

**Issue by maackle** [LedgerHQ/ledger-live-desktop#2524]
#### Ledger Live Version and Operating System

- tested on Ledger Live 1.18.2
- Platform and version: Linux Mint 18.04

#### Expected behavior

In my wallet, when viewing the conversion rate for my HoloToken (HOT), I should see the correct rate

#### Actual behavior

I see the conversion rate for the *other* HOT (Hydro Protocol) instead, even though the wallet shows correctly that it thinks it is using HoloToken

#### Steps to reproduce the behavior

1. Create an Ethereum wallet
2. Receive HoloToken
3. See the incorrect balance and conversion rate

![ledger-problem-annotated](https://user-images.githubusercontent.com/896230/69889394-7b8d8f00-12a5-11ea-8137-cbc88487a819.png)

**Comment by gre** [comment]
unfortunately with the current ticker collision between Holo ( https://coinmarketcap.com/fr/currencies/holo/ ) and Hot ( https://coinmarketcap.com/fr/currencies/hot-token/ ), there is no easy solution to fix this problem in current architecture and in exchanges in general (ticker is used as identifier for exchange) and we've decided to disable the countervalues of both.

We will forward the problem to our rate provider.

**Comment by gre** [comment]
We expect this to be fixed in context of a big rework that just got merged. we'll reopen in this does not fix in the next release https://github.com/LedgerHQ/ledger-live-desktop/pull/2596

**Comment by zargony** [comment]
I just installed Ledger Live 2.1.0 and HoloToken (HOT) doesn't show any countervalue in my accounts and in Settings -> Crypto Assets, there's no entry to select a rate provider for HOT anymore.

To me it looks like the above MR #2596 is included in release 2.1.0, so it seems like this problem didn't get fixed by it?

**Comment by gusluke** [comment]
> I just installed Ledger Live 2.1.0 and HoloToken (HOT) doesn't show any countervalue in my accounts and in Settings -> Crypto Assets, there's no entry to select a rate provider for HOT anymore.
> 
> To me it looks like the above MR #2596 is included in release 2.1.0, so it seems like this problem didn't get fixed by it?

I'm having the same problem, can see the amount of HOT in ledger live but it is not showing any price at all.

Any idea why this will be solved?

Thanks

**Comment by gre** [comment]
@FabriceDautriat should we assume that HOT is Holo and put it back on? HOT Token seems dead?

- https://coinmarketcap.com/fr/currencies/holo/
- https://coinmarketcap.com/fr/currencies/hot-token/

**Comment by FabriceDautriat** [comment]
Hey @gre ,

IMO the issue remains. HOT (Holo tokens) and HOT (hydro protol) are still both traded.

But it's true Hydro Protocol is now way less traded than Holo token.

We could definitely reactivate the coutervalue for Holo token, but is there a way for us to remove the following pairs for Hydro Protocol ?

![image](https://user-images.githubusercontent.com/44614987/81145078-cf4b8500-8f75-11ea-8c9e-99032f825bd1.png)

**Comment by zargony** [comment]
I don't know the LedgerLive internals, but from what I understand, the problem is that two different tokens use the same name and LedgerLive identifies them by name and therefore can't distinguish them.

So the obvious fix would be to use a unique identifier instead (e.g. contract address)? I suppose that'd cause many internal changes and is undesired because it's a lot of work.

In a comment above on Feb 20, @gre mentioned that this is expected to be fixed with #2596, but obviously it isn't?

Even with the duplicate name problem, can't we just get back the usual countervalues and choose the correct token by selecting a rate provider in settings? This would allow people with either token to display countervalues. To be on the safe side, it could be made an explicit choice by using no rate provider for the token by default, but let the user choose one.

**Comment by gre** [comment]
we'll discuss this internally. unfortunately at countervalues and exchange level, the ticker is the way to identify coins in markets. So there is no easy solution but to do some arbitrary choices at one part of the chain of services that are behind the Live->Exchange.

We're planning on reworking our countervalues in Ledger Live at the moment so we're going to take this into account in our iterations (among other constraints).

**Comment by zargony** [comment]
@gre has there been any progress on this by any chance? I just updated my Ledger Live to 2.9.0 and it's a bit disappointing to see that it still doesn't display the countervalue of HOT. Older versions of Ledger Live used to display it fine.

**Comment by cthepot-ledger** [comment]
Working on a new counter value implementation that will fix this issue as per the attached duplicate issue. Thank you for reporting it.

Duplicate of #2326

**Comment by zargony** [comment]
I just installed v2.20.0 which claims "All known countervalue bugs are fixed!", but HOT still displays no countervalue.

**Comment by gre** [comment]
just a precision on this, it's a token / maintenance topic, we misflagged it as related to #2326 but it was independent. It's more about the configuration of a specific token.

This commit https://github.com/LedgerHQ/ledgerjs/blob/master/packages/cryptoassets/data/erc20.js just landed in ledgerjs and will be part of 2.21.0
it includes the enabling of HOT.
