### ISSUE TITLE
ALGO synchronization not possible if opted in to ASA asset YLDY

### ISSUE THREAD

**Issue by RetroHazard** [LedgerHQ/ledger-live-desktop#4226]
#### Ledger Live Version and Operating System
WIndows 10, Ledger Live 2.33.1

#### Expected behavior
Should be able to add ALGO account to Ledger Live

#### Actual behavior
Ledger Live begins synchronization and immediate fails out with the following error.
> Internal process error (3221226505)
> Something went wrong. Please retry or contact Ledger Support.

#### Steps to reproduce the behavior
1. Create ALGO address/add account
2. Opt-in to Yieldly contract(s) @ app.yieldly.finance (ASA ID: 226701642)
3. Remove ALGO address (or reset Ledger Live)
4. Try to re-add ALGO address
_Reproduction of issue does not require any YLDY to be present in address or staking to occur._

**Comment by erdnapa** [comment]
Can confirm. 
ALL accounts (eth, btc, algo etc) on Ledger are unusable in Ledger Live once asset is added to a Algorand account. 
Removing the asset from the account does NOT fix the issue, all accounts remain unusable, no sending etc., rendering the Ledger unusable.
(Ledger X, 2.32.2 and 2.33.1)

**Comment by brettseven** [comment]
I am experiencing this as well. One other thing is that if I try to add my Algorand account and then close Ledger Live, it doesn't reopen unless I go into task manager and kill it.

**Comment by er-eis** [comment]
Same issue. As @erdnapa points out, this issue renders Ledger unusable.

**Comment by erdnapa** [comment]
> Same issue. As @erdnapa points out, this issue renders Ledger unusable.

A workaround to get ledger back to function: 
1. Link the Ledger ASA algo account to MyAlgo wallet. 
2. Create a second MyAlgo wallet ('add wallet' button, new seed etc) in the MyAlgo wallet (this is non-ledger)
3. Move all ASA from ledger to new non-ledger MyAlgo wallet
4. Remove all ASA from ledger algo account (in MyAlgo wallet), make it a non-ASA account.
5. Reboot/kill all hanging Ledger processes. 
Ledger works again (at least for me), but ASA now in MyAlgo wallet only.

**Comment by er-eis** [comment]
> > Same issue. As @erdnapa points out, this issue renders Ledger unusable.
> 
> A workaround to get ledger back to function:
> 
> 1. Link the Ledger ASA algo account to MyAlgo wallet.
> 2. Create a second MyAlgo wallet ('add wallet' button, new seed etc) in the MyAlgo wallet (this is non-ledger)
> 3. Move all ASA from ledger to new non-ledger MyAlgo wallet
> 4. Remove all ASA from ledger algo account (in MyAlgo wallet), make it a non-ASA account.
> 5. Reboot/kill all hanging Ledger processes.
>    Ledger works again (at least for me), but ASA now in MyAlgo wallet only.

Sure, this will make Ledger Live work again. But it means your ASAs are no longer secured with Ledger hardware.

**Comment by goliszewski** [comment]
Ledger Team! It works on mobile! But not on desktop?

**Comment by cullanshewfelt** [comment]
I am also having this issue. Hope it gets resolved in the next update. Seems like a lot of people's funds are inaccessible.

**Comment by Sleinous** [comment]
Same issue here, when can we expect this to be fixed?

**Comment by jeffsmith8** [comment]
Same issue here, it has been going on for months. Between this issue and ledger communication failing on Chrome its been a real mess. Please fix!!!

Temporary fix - install ledger live on a different device and do not add ASA support.
Reinstalling ledger live does not fix the problem because the config files are left on the OS after unistalling.

**Comment by sdherr** [comment]
I have the same problem. Attached is my log file.
[ledgerlog.zip](https://github.com/LedgerHQ/ledger-live-desktop/files/7872055/ledgerlog.zip)

**Comment by cccassidy** [comment]
Same here following the steps of the original posting, this was on a new 2nd algo account I created.

Was I was able to get the account to finally re-add by enabling the "Experimental JS Implementations" option but now I can't get any transactions to go through on either the original or 2nd algo account.  New error message shows:

`msgpack decode error [pos 1]: only encoded map or array can be decoded into a struct`

**Comment by tonteron** [comment]
@Ledger_Support I want to share the fix for sync issue in Algorand wallet. With current version of Ledger Live, ASA's make account unsyncable, which is completely in line with what is described above. I had to open accounts in @myalgo_ wallet and delete ASA's. Fortunately I didn't have anything of value there, but this shouldn't be this way. How can we expect mass adoption if we can't make it more seamless and secure!

PLEASE FIX THIS! Need hardware solutions to work.

@Algorand @Ledger @Reddit @Timbonacci702 @PandALGOs
